CREATE TABLE IF NOT EXISTS students (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    nim VARCHAR(12) NOT NULL UNIQUE CHECK (nim ~ '^[0-9]{12}$'),
    nama VARCHAR(150) NOT NULL,
    prodi VARCHAR(150) NOT NULL,
    angkatan SMALLINT NOT NULL CHECK (angkatan BETWEEN 1000 AND 9999),
    ipk_terakhir NUMERIC(3,2) NOT NULL DEFAULT 0.00 CHECK (ipk_terakhir BETWEEN 0.00 AND 4.00),
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
