CREATE TABLE IF NOT EXISTS courses (
    id BIGSERIAL PRIMARY KEY,
    kode_mk VARCHAR(20) NOT NULL UNIQUE,
    nama_mk VARCHAR(200) NOT NULL,
    sks SMALLINT NOT NULL CHECK (sks BETWEEN 1 AND 6),
    semester SMALLINT NOT NULL CHECK (semester BETWEEN 1 AND 14),
    kuota INTEGER NOT NULL CHECK (kuota > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
